ITEMS = {
    1: "Displacement",
    2: "Autistic Fantasy",
    3: "Splitting Other",
    4: "Intellectualization",
    5: "Acting Out",
    6: "Splitting Other",
    7: "Omnipotence",
    8: "Dissociation",
    9: "Self Observation",
    10: "Omnipotence",
    11: "Altruism",
    12: "Devaluation Self",
    13: "Repression",
    14: "Sublimation",
    15: "Altruism",
    16: "Idealization Other",
    17: "Idealization Other",
    18: "Humor",
    19: "Rationalization",
    20: "Denial",
    21: "Help Rejecting Complaining",
    22: "Affiliation",
    23: "Self Assertion",
    24: "Autistic Fantasy",
    25: "Affiliation",
    26: "Intellectualization",
    27: "Dissociation",
    28: "Isolation of Affect",
    29: "Devaluation Self",
    30: "Dissociation",

    31: "Isolation of Affect",
    32: "Self Observation",
    33: "Denial",
    34: "Devaluation Self",
    35: "Splitting Self",
    36: "Sublimation",
    37: "Humor",
    38: "Idealization Self",
    39: "Isolation of Affect",
    40: "Humor",
    41: "Dissociation",
    42: "Rationalization",
    43: "Anticipation",
    44: "Affiliation",
    45: "Passive Aggression",
    46: "Anticipation",
    47: "Repression",
    48: "Undoing",
    49: "Suppression",
    50: "Repression",
    51: "Humor",
    52: "Reaction Formation",
    53: "Intellectualization",
    54: "Devaluation Other",
    55: "Reaction Formation",
    56: "Devaluation Self",
    57: "Intellectualization",
    58: "Self Observation",
    59: "Rationalization",
    60: "Intellectualization",

    61: "Splitting Self",
    62: "Anticipation",
    63: "Sublimation",
    64: "Displacement",
    65: "Anticipation",
    66: "Affiliation",
    67: "Undoing",
    68: "Omnipotence",
    69: "Displacement",
    70: "Undoing",
    71: "Idealization Self",
    72: "Projective Identification",
    73: "Dissociation",
    74: "Reaction Formation",
    75: "Projective Identification",
    76: "Acting Out",
    77: "Self Observation",
    78: "Anticipation",
    79: "Altruism",
    80: "Acting Out",
    81: "Undoing",
    82: "Devaluation Other",
    83: "Undoing",
    84: "Help Rejecting Complaining",
    85: "Devaluation Other",
    86: "Rationalization",
    87: "Idealization Self",
    88: "Passive Aggression",
    89: "Passive Aggression",
    90: "Self Assertion",

    91: "Self Observation",
    92: "Splitting Self",
    93: "Affiliation",
    94: "Splitting Self",
    95: "Idealization Other",
    96: "Reaction Formation",
    97: "Sublimation",
    98: "Splitting Other",
    99: "Reaction Formation",
    100: "Sublimation",
    101: "Projective Identification",
    102: "Passive Aggression",
    103: "Projective Identification",
    104: "Altruism",
    105: "Self Assertion",
    106: "Autistic Fantasy",
    107: "Isolation of Affect",
    108: "Repression",
    109: "Self Assertion",
    110: "Autistic Fantasy",
    111: "Devaluation Other",
    112: "Projection",
    113: "Projective Identification",
    114: "Splitting Self",
    115: "Projection",
    116: "Passive Aggression",
    117: "Suppression",
    118: "Acting Out",
    119: "Humor",
    120: "Rationalization",

    121: "Denial",
    122: "Displacement",
    123: "Projection",
    124: "Denial",
    125: "Displacement",
    126: "Omnipotence",
    127: "Help Rejecting Complaining",
    128: "Suppression",
    129: "Omnipotence",
    130: "Help Rejecting Complaining",
    131: "Suppression",
    132: "Altruism",
    133: "Idealization Self",
    134: "Projection",
    135: "Idealization Self",
    136: "Repression",
    137: "Denial",
    138: "Idealization Other",
    139: "Idealization Other",
    140: "Isolation of Affect",
    141: "Projection",
    142: "Splitting Other",
    143: "Devaluation Other",
    144: "Acting Out",
    145: "Splitting Other",
    146: "Self Assertion",
    147: "Devaluation Self",
    148: "Autistic Fantasy",
    149: "Help Rejecting Complaining",
    150: "Suppression"
}







MECHANISMS = {
    0: {
        'mechanism_name': 'No Defenses',
        'mechanisms': 'N/A',
        'definition': 'Purely functional utterances that serve to maintain conversational flow, express social niceties, or exchange non-emotional information. They do not engage with psychological conflict.',
        'example': 'Hello, thank you for your time, or a simple "Okay."'
    },
    1: {
        'mechanism_name': 'Action Defenses',
        'mechanisms': 'Passive Aggression, Help-Rejecting Complaining, Acting Out',
        'definition': 'Action defenses reflect the perception of the individual that the immediate source of stress or conflict is external and that the experience is intolerable. The individual’s perception overlooks the internal sources of the distress, such as personal unacceptability of or limitations in awareness of one’s own wishes, fears, and inhibitions. Unable to contain attendant distress, these defenses operate to engage, manipulate, or counterattack the apparent external source. These defenses lead the individual to impulsive action on the environment or oneself, thereby releasing tension, gratifying wishes, and/or avoiding fears. However, this is done without anticipating negative consequences.',
        'example': 'After being criticized at work, a person goes home and starts a fight over something minor.'
    },
    2: {
        'mechanism_name': 'Major Image-Distorting Defenses',
        'mechanisms': 'Splitting, Projective Identification',
        'definition': 'Major image-distorting defenses protect the individual from intolerable anxiety when self or object representations of conflicting meaning are triggered. The individual keeps positive and negative representations separated and simplify the perception of self and others as either all good, powerful, and invulnerable or all bad, unworthy, powerless, and vulnerable. The individual then treats these distorted images in ways consistent with this perception. These defenses protect the self from the anxiety attending a sense of imminent threat of being punished, physically or psychologically abused, abandoned, or even killed. However, oversimplifying self or others and reacting accordingly produces the negative consequent that others withdraw or react negatively.',
        'example': '"My boss is either a genius or completely incompetent."'
    },
    3: {
        'mechanism_name': 'Disavowal defenses and autistic fantasy',
        'mechanisms': 'Denial, Rationalization, Projection, Autistic Fantasy',
        'definition': 'Disavowal defenses reflect the perception of the individual that some aspects of internal experience external reality are unacceptable. By refusing to acknowledge these aspects of experience, the individual justifies not appropriating a problem as his or her own. The individual cafurther misattribute the problem to another source or reason, further covering up internal reality. This results in a failure both to acknowledge one’s own role in the origins of a problem and to consider potential ways of handling the immediate problem, given the assertion that one hano such role.',
        'example': '"I didn’t get promoted because my boss is biased, not because of my performance."'
    },
    4: {
        'mechanism_name': 'Minor Image-Distorting Defenses',
        'mechanisms': 'Devaluation, Idealization, Omnipotence',
        'definition': 'Minor image-distorting defenses protect the individual from experiences that affect one’s self esteem, such as failure, criticism, or disappointment that cause feelings of weakness, powerlessness, or shame. These defenses temporarily prop up self-esteem and strengthen self-image by using image-distortion to dismiss any threatening aspect of the stressor. These distortions are not all encompassing like those of the major image-distorting defenses. Nonetheless, they don’t actually improve adaptation to the stressors.',
        'example': '"They only succeeded because of luck—anyone could do that."'
    },
    5: {
        'mechanism_name': 'Neurotic Defenses',
        'mechanisms': 'Repression, Dissociation, Reaction Formation, Displacement',
        'definition': 'Neurotic defenses reflect the experience that awareness of a wish, thought, or motive is unacceptable or threatening and must be kept out oawareness. The individual can experience feelings associated to an internal conflict or external stressor as long as full awareness of the idea (cognitive component) is blocked and expressed indirectly by way of a series of anomalous clues. Neurotic defenses are the most protean of all defense mechanisms, in that there are a seemingly infinite variety of ways to give partial expression of repressed ideas.',
        'example': 'Feeling irritable all day without knowing why, then realizing it’s tied to a painful memory.'
    },
    6: {
        'mechanism_name': 'Obsessional Defenses',
        'mechanisms': 'Isolation of Affect, Intellectualization, Undoing',
        'definition': 'Obsessional defenses protect the individual from the awareness of unacceptable or threatening feelings associated with an idea (e.g., wish, fear, experience, memory, or though) by keeping distance from emotions, while remaining aware of the idea itself. As a result, feelings (emotional component) are largely kept out of awareness and indirectly expressed throughout minimization, generalization, or a series of contradictory statements.',
        'example': 'Describing a traumatic accident in a highly technical, emotionless way.'
    },
    7: {
        'mechanism_name': 'High-Adaptive Defenses',
        'mechanisms': 'Affiliation, Altruism, Anticipation, Humor, Self-Assertion, Self-Observation, Sublimation, Suppression',
        'definition': 'High adaptive defenses are the individual’s most adaptive ways of handling stressors and are often considered synonymous of positive coping. Internal or external stressors are fully perceived without distortion and the need to adapt to them is fully appropriated to oneself. The individual attempts to maximize the positive expression and gratification of his or her own motives, acknowledging limitations of the self and recurring to external sources of help when available.',
        'example': '"I’m overwhelmed, so I’ll ask a colleague for help and plan my next steps."'
    },
    8: {
        'mechanism_name': 'Needs More Information',
        'mechanisms': 'N/A',
        'definition': 'Used when an utterance is too ambiguous or lacks sufficient context to determine the defense mechanism.',
        'example': 'A vague response like "maybe" to an emotional question.'
    }
}